Rellenado de check en Gustavo Saldaña. Resuelve #<12>
santiagosilvestrini/trabajo-final-2024 pull request #16
Opened 2024-05-04 21:12 UTC by Gugui22

Resuelta la parte 3 del ejercicio, agregando una x entre corchetes desde el escritorio.

2024-05-11 01:21 UTC, santiagosilvestrini commented
En este PR también hiciste la referencia con los <>. Notá que si vas al issue no vas a ver que está enlazado al PR. Si la referencia es correcta deberías ver algo así en el Issue: 
![image](https://github.com/santiagosilvestrini/trabajo-final-2024/assets/2256587/d62e8feb-9cc3-4318-bdb7-f6cde23d66e4)

2024-05-11 02:24 UTC, santiagosilvestrini requested changes
No cumple con la consigna. No tenías que marcar todas las casillas, solo las de tu nombre.
Por favor enviá otro commit resolviendo este tema. Utilizá la misma rama así queda toda la historia en el log.

2024-05-11 22:29 UTC, Gugui22 commented
Santiago, ahi saque los <> y volvi a realizar la subida.

2024-05-12 00:27 UTC, santiagosilvestrini commented
Cierro este PR. Ya hice el merge de los PR #6 y #11.

2024-05-12 00:28 UTC, santiagosilvestrini commented
Cierro este PR. Ya hice el merge de los PR https://github.com/santiagosilvestrini/trabajo-final-2024/pull/6 y https://github.com/santiagosilvestrini/trabajo-final-2024/pull/11.

2024-05-12 00:28 UTC, closed without merging